/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;


import javax.swing.JLabel;
import java.awt.event.*;
import javax.swing.*;

public class Login extends javax.swing.JFrame {

    public Login() {

        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("로그인");
        setAutoRequestFocus(false);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(null);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 450));

        jPanel5.setMaximumSize(null);
        jPanel5.setPreferredSize(new java.awt.Dimension(600, 450));
        jPanel5.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel1.setLayout(null);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()-1f));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("아이디");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 10, 40, 20);

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()-1f));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("비밀번호");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 50, 20);

        jTextField1.setFont(jTextField1.getFont().deriveFont(jTextField1.getFont().getSize()-1f));
        jTextField1.setNextFocusableComponent(jButton2);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(77, 10, 110, 24);

        jPasswordField1.setFont(jPasswordField1.getFont().deriveFont(jPasswordField1.getFont().getSize()-1f));
        jPasswordField1.setToolTipText("");
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(77, 40, 110, 24);

        jButton1.setFont(jButton1.getFont().deriveFont(jButton1.getFont().getSize()-1f));
        jButton1.setText("회원가입");
        jButton1.setPreferredSize(new java.awt.Dimension(70, 21));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 70, 80, 21);

        jButton2.setFont(jButton2.getFont().deriveFont(jButton2.getFont().getSize()-1f));
        jButton2.setText("로그인");
        jButton2.setPreferredSize(new java.awt.Dimension(70, 21));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(117, 70, 70, 21);

        jPanel5.add(jPanel1);
        jPanel1.setBounds(200, 300, 200, 100);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(Base.Img("https://blog.kakaocdn.net/dn/bbxCGe/btq5Q6gUzU6/E9pkCraFe75pW2VniXd801/img.jpg"));
        jLabel3.setAlignmentX(0.5F);
        jPanel5.add(jLabel3);
        jLabel3.setBounds(0, 0, 600, 450);
        jPanel5.add(jLabel4);
        jLabel4.setBounds(195, 295, 211, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String ID = jTextField1.getText();
        String PW = new String(jPasswordField1.getPassword());
        //if(false){  //Server의 user info랑 비교
            JOptionPane.showMessageDialog(null, new JLabel("등록된 계정이 없습니다.", JLabel.CENTER), "메세지", JOptionPane.WARNING_MESSAGE);
            jTextField1.setText("");
            jPasswordField1.setText("");
        //}
        //else{
            //매치 될 경우 접속
         //}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //if(false){  //Server의 user info랑 ID 비교
            JOptionPane.showMessageDialog(null, new JLabel("이미 등록된 계정입니다.", JLabel.CENTER), "메세지", JOptionPane.WARNING_MESSAGE);
            jTextField1.setText("");
            jPasswordField1.setText("");
        //}
        //else{ //매치 될 경우
            //JOptionPane.showMessageDialog(null, new JLabel("가입이 완료되었습니다.", JLabel.CENTER), "메세지", JOptionPane.PLAIN_MESSAGE);    //가입
            //접속
        //}
    }//GEN-LAST:event_jButton1ActionPerformed

    //static JFrame frm;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton2;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel5;
    javax.swing.JPasswordField jPasswordField1;
    javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
