/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;


import javax.swing.JLabel;
import java.awt.event.*;
import javax.swing.*;

public class Login extends javax.swing.JFrame {

    public Login() {

        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_screen = new javax.swing.JPanel();
        Panel_name = new javax.swing.JPanel();
        Label_name = new javax.swing.JLabel();
        TextField_name = new javax.swing.JTextField();
        Button_login = new javax.swing.JButton();
        Label_screen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("로그인");
        setAutoRequestFocus(false);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(null);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 450));

        Panel_screen.setMaximumSize(null);
        Panel_screen.setPreferredSize(new java.awt.Dimension(600, 450));
        Panel_screen.setLayout(null);

        Panel_name.setBackground(new java.awt.Color(255, 255, 255));
        Panel_name.setAlignmentX(0.0F);
        Panel_name.setAlignmentY(0.0F);
        Panel_name.setMinimumSize(new java.awt.Dimension(200, 100));
        Panel_name.setPreferredSize(new java.awt.Dimension(200, 100));
        Panel_name.setLayout(null);

        Label_name.setFont(Label_name.getFont().deriveFont(Label_name.getFont().getSize()-1f));
        Label_name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Label_name.setText("닉네임");
        Label_name.setToolTipText("");
        Panel_name.add(Label_name);
        Label_name.setBounds(10, 10, 40, 20);

        TextField_name.setFont(TextField_name.getFont().deriveFont(TextField_name.getFont().getSize()-1f));
        TextField_name.setNextFocusableComponent(Button_login);
        Panel_name.add(TextField_name);
        TextField_name.setBounds(60, 10, 110, 24);

        Button_login.setFont(Button_login.getFont().deriveFont(Button_login.getFont().getSize()-1f));
        Button_login.setText("로그인");
        Button_login.setPreferredSize(new java.awt.Dimension(70, 21));
        Button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_loginActionPerformed(evt);
            }
        });
        Panel_name.add(Button_login);
        Button_login.setBounds(90, 40, 80, 21);

        Panel_screen.add(Panel_name);
        Panel_name.setBounds(200, 300, 190, 70);

        Label_screen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_screen.setIcon(Base.Img("https://blog.kakaocdn.net/dn/bbxCGe/btq5Q6gUzU6/E9pkCraFe75pW2VniXd801/img.jpg"));
        Label_screen.setAlignmentX(0.5F);
        Panel_screen.add(Label_screen);
        Label_screen.setBounds(0, 0, 600, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Panel_screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_loginActionPerformed(ActionEvent evt) {//GEN-FIRST:event_Button_loginActionPerformed
        String ID = TextField_name.getText();
        //if(false){  //Server의 user info랑 비교
            JOptionPane.showMessageDialog(null, new JLabel("등록된 닉네임이 있습니다.", JLabel.CENTER), "메세지", JOptionPane.WARNING_MESSAGE);
            TextField_name.setText("");
        //}
        //else{
            //등록된 닉네임 없을 경우 접속
         //}
    }//GEN-LAST:event_Button_loginActionPerformed

    //static JFrame frm;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton Button_login;
    javax.swing.JLabel Label_name;
    javax.swing.JLabel Label_screen;
    javax.swing.JPanel Panel_name;
    javax.swing.JPanel Panel_screen;
    javax.swing.JTextField TextField_name;
    // End of variables declaration//GEN-END:variables
}
